### ISSUE TITLE
TL-WR84x image mit Antennen

### ISSUE THREAD

**Issue by rubo77** [Moorviper/Freifunk-Router-Anleitungen#2]
Ich finde deine Bilder echt alle sehr schick, bis auf die abgeschnittenen Antennen beim 841.

https://github.com/Moorviper/Freifunk-Router-Anleitungen/blob/master/router/tp-link-tl-wr841n-nd-v10/front.svg

kannst du die nicht wieder ergänzen, so wie vorher?
<img src="https://nord.freifunk.net/images/models/tp-link-tl-wr841n-nd_100x60.png">

hattest du ja früher so drin:

https://github.com/Moorviper/Freifunk-Router-Anleitungen/blob/d756e22f1e08bd191c39e874d3bf476abff50e27/tp-link-tl-wr841n-nd-v10/front.jpg

**Comment by Moorviper** [comment]
ja habe ich noch vor die Draufsicht war ein schneller fix da die erste Version schlecht gezeichnet war und sich nicht ordentlich einfärben lies.
Ab April mache ich weiter.

**Comment by Moorviper** [comment]
https://raw.githubusercontent.com/Moorviper/Freifunk-Router-Anleitungen/master/router/tp-link-tl-wr741n-nd-v5/front.jpg

der rest kommt in einer ruhigen minute ;-)
Die gehash'ten im anderen repo danach
